dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

cache:
  directories:
    - $HOME/.cache/apt

before_install:
  - echo "Installing C++ and Python"
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends --no-install-suggests g++ python-dev python3-dev python3-pip maven libnuma-dev libc-dev python3-venv  openmpi-bin libopenmpi-dev flex bison libomp-dev
  - sudo apt-get install gsl-bin libgsl0-dev libboost-all-dev
  - cp /var/cache/apt/archives/*.deb $HOME/.cache/apt/
  - export BOOST_LIBDIR=/usr/lib/x86_64-linux-gnu/

jobs:
  include:
    - stage: "Build Stages"
      script:
        - make
      name: "Build Project"